#!/usr/bin/env python3
"""
Setup Script for Phishing Detection Project

This script creates a .env file with secure default values.
The .env file is automatically ignored by git (.gitignore includes *.env).

Usage:
    python setup_env.py

Author: Phishing Guard Team
"""

import os
import secrets

# Generate secure JWT secret
JWT_SECRET = secrets.token_hex(32)

# Template for .env file
ENV_CONTENT = f"""# Phishing Detection Project - Environment Configuration
# Generated by setup_env.py
# Never commit this file to version control!

# ==========================================
# Security Settings (REQUIRED)
# ==========================================

# JWT Secret for API authentication
# Generated automatically - DO NOT SHARE
JWT_SECRET={JWT_SECRET}

# JWT Token Expiration (hours)
JWT_EXPIRATION_HOURS=24

# ==========================================
# Server Configuration
# ==========================================

HOST=0.0.0.0
PORT=8000
ENVIRONMENT=development
ENABLE_HTTPS=false

# ==========================================
# API Configuration
# ==========================================

RATE_LIMIT_REQUESTS=100
RATE_LIMIT_WINDOW=60

# ==========================================
# Redis Configuration (Optional)
# ==========================================

REDIS_URL=

# ==========================================
# MLLM Configuration (Optional)
# ==========================================

LOAD_MLLM=false
OLLAMA_URL=http://localhost:11434
MLLM_MODEL=qwen2.5-vl-7b-instruct

# ==========================================
# Feature Configuration
# ==========================================

ENABLE_SCRAPING=true
ENABLE_TLS_ANALYSIS=true

# ==========================================
# Logging Configuration
# ==========================================

LOG_LEVEL=INFO
LOG_FILE=./08_logs/api.log

# ==========================================
# Browser Extension Configuration
# ==========================================

EXTENSION_API_URL=http://localhost:8000

# ==========================================
# Development Settings
# ==========================================

RELOAD=true
DEBUG=false
"""

def main():
    env_file = ".env"
    
    if os.path.exists(env_file):
        response = input(f"{env_file} already exists. Overwrite? (y/n): ")
        if response.lower() != 'y':
            print("Setup cancelled.")
            return
    
    with open(env_file, 'w') as f:
        f.write(ENV_CONTENT)
    
    print(f"✓ Created {env_file} with secure defaults")
    print(f"✓ JWT_SECRET automatically generated")
    print("\nTo start the API server, run:")
    print("    conda run -n phishing-detection-mllm uvicorn 04_inference.api:app --reload")
    print("\nOr use demo.py:")
    print("    conda run -n phishing-detection-mllm python demo.py")

if __name__ == "__main__":
    main()
